v: 2.6.0
overrideConfig: q
ie:
    - DS_Store
    - less
    - scss
id:
    - scss
    - .svn
    - .sass-cache
cleanPublic: 'true'
patternStates:
    - inprogress
    - inreview
    - complete
styleGuideExcludes: ''
cacheBusterOn: 'true'
exportDir: export
publicDir: public
sourceDir: source
assetsDirDefault: /assets
defaultPattern: documentation-intro
defaultShowPatternInfo: true
lineageMatch: '{%([ ]+)?(?:include|extends|embed)( |\()[&quot;\&#039;]([\/.@A-Za-z0-9-_]+)[&quot;\&#039;]([\s\S+]*?)%}'
lineageMatchKey: 3
patternExtension: twig
twigDebug: true
twigAutoescape: html
twigDefaultDateFormat: ''
twigDefaultIntervalFormat: ''
twigMacroExt: macro.twig
twigFilterExt: filter.php
twigFunctionExt: function.php
twigTagExt: tag.php
twigTestExt: test.php
ishMinimum: '320'
ishMaximum: '2600'
ishControlsHide:
    - hay
    - views-all
ishViewportRange:
    s:
        - 320
        - 719
    m:
        - 720
        - 1023
    l:
        - 1024
        - 1279
styleguideKit: pattern-lab/styleguidekit-twig-default
styleguideKitPath: vendor/pattern-lab/styleguidekit-twig-default
plugins:
    reload:
        enabled: true
    dataInheritance:
        enabled: false
    twigNamespaces:
        enabled: true
        roots: {  }
        namespaces: { docs: { recursive: false, paths: [docs] } }
